;;; company-plsense-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-plsense.el

(autoload 'company-plsense-setup "company-plsense" "\
Setup the default ‘company-plsense’ configuration.
This will start the server and enable command `company-mode'
with the appropriate major modes." t)
(autoload 'company-plsense "company-plsense" "\
Company backend for PlSense server.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-plsense" '("company-plsense-"))

;;; End of scraped data

(provide 'company-plsense-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-plsense-autoloads.el ends here
