;;; edbi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from edbi.el

(autoload 'edbi:open-db-viewer "edbi" "\
Open Database viewer buffer." t)
(register-definition-prefixes "edbi" '("edbi:"))

;;; End of scraped data

(provide 'edbi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; edbi-autoloads.el ends here
